sudo: required
dist: trusty
language: node_js

node_js:
  - "8"

env:
  - SENECA_VER=seneca@3.x.x
  - SENECA_VER=seneca@plugin
  - SENECA_VER=senecajs/seneca

before_script:
  - npm uninstall seneca
  - npm install $SENECA_VER

after_script:
  - npm run coveralls
